### ISSUE TITLE
Plus doesn't run on SonixTouch running Windows XP

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#200]
When trying to start Plus on a SonixTouch machine, the following message appears:

PlusServer.exe - Entry Point Not Found
The procedure entry point inet_ntop could not be located in the dynamic link library WS2_32.dll

It seems to be a problem with Windows XP, possibly related to [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/e40465f2-41b7-4243-ad33-15ae9366f4e6/winsock2-error-the-procedure-entry-point-xxxx-cold-not-be-located-in-ws232dll?forum=vcgeneral).

There is one call to inet_ntop in Plus [here](https://github.com/PlusToolkit/PlusLib/blob/6b8de087d98764ae8fca1597d5db0c46f672aa69/src/PlusDataCollection/Philips3D/vtkPlusPhilips3DProbeVideoSource.cxx#L255).

**Comment by adamrankin** [comment]
The Philips code can't be built at the same time as Sonix (conflicting API
dlls), so it won't be that call.

I've seen this before, but can't remember. Andras I think knew the right
solution.

Adam

**Comment by Sunderlandkyl** [comment]
It seems to be caused by something in OpenIGTLink. I'm going to dig a little deeper to try and find the exact issue.

**Comment by Sunderlandkyl** [comment]
I've found that it's due to one (or both) of the inet_pton calls at:

https://github.com/openigtlink/OpenIGTLink/blob/ed497dedc6251ebf1e1b86a55ee0daef86bedc2c/Source/igtlUDPServerSocket.cxx#L62

and 

https://github.com/openigtlink/OpenIGTLink/blob/ed497dedc6251ebf1e1b86a55ee0daef86bedc2c/Source/igtlGeneralSocket.cxx#L572

**Comment by adamrankin** [comment]
Was the last successful XP build on Jan 26?

**Comment by Sunderlandkyl** [comment]
I'm not sure to be honest.

There was an existing build from August on the Sonix touch which did not work, so sometime before then.

The stable build is working fine.

**Comment by leochan2009** [comment]
Hi Both,
compile issue should be fixed by your pull request.
Thanks a lot!.

Best,
Longquan

**Comment by adamrankin** [comment]
Thanks!

**Comment by Sunderlandkyl** [comment]
Apparently the nightly version still doesn't run on XP, since it's built with support for Phidget Spatial (which also has an inet_ntop/inet_pton call).

Do we need to have support for Phidget Spatial in the Ultrasonix builds, or can I just disable it?
